"""Bounded merge-tree reduction (Spec 026 T012, T012a).

Exercises `composer_reduce.compose()`'s merge phase directly (via
`batching.partition()` + a scripted `stub_caller`) with a deliberately tiny
`BatchingLimits` so a handful of small fragments force the pairwise-tree
fallback instead of one flat merge.
"""

from __future__ import annotations

import json
import threading
from pathlib import Path

import pytest

from spaex.behavior.composer import batching
from spaex.behavior.composer import invoke as composer_invoke
from spaex.behavior.composer import reduce as composer_reduce
from spaex.behavior.composer.clarifications import ClarificationsStore
from spaex.behavior.composer.failure import ComposerInvalidOutputError
from spaex.behavior.composer.invoke import InvokeOptions
from spaex.behavior.fragment import BehaviorFragment


def _fragment(molecule: str, body: str) -> BehaviorFragment:
    """Build one fragment for a merge-tree scenario."""
    raw = (
        f"---\nid: rule\nkind: constitution_fragment\n"
        f"atom_source: pkg.a\nmodality: MUST\n---\n{body}\n"
    ).encode()
    return BehaviorFragment.from_bytes(raw, molecule_id=molecule, path=f"{molecule}/rule.md")


def _batch_stub_response(payload: str) -> str:
    """Shape A for a batch call: one bullet citing that batch's fragment."""
    data = json.loads(payload)
    fragment = data["fragments"][0]
    scoped = f"{fragment['molecule_id']}/{fragment['fragment_id']}"
    body = f"## MUST\n\n- {fragment['body'].strip()} _[from `{scoped}`]_\n"
    return (
        "<<<SPAEX-COMPOSER-BEGIN>>>\n"
        '{"type": "composed", "questions": []}\n'
        "<<<SPAEX-COMPOSER-END>>>\n\n" + body
    )


def _merge_stub_response(payload: str, *, is_root: bool) -> str:
    """Shape A for a merge call: concatenate every input body's bullets."""
    data = json.loads(payload)
    bullets: list[str] = []
    for bc in data["batch_compositions"]:
        for line in bc["body"].splitlines():
            if line.startswith("- "):
                bullets.append(line)
    header = ""
    if is_root:
        header = (
            f'<!-- spaex-composed:source_hash="{data["expected_source_hash"]}" '
            f'build_input_hash="{data["expected_build_input_hash"]}" version="1" -->\n'
            "# spaex Behavior Harness\n\n"
            "_This file is generated by `spaex install`. Do not edit by hand._\n"
            "_Change fragments in `.spaex/constitution.d/` and re-run install._\n\n"
        )
    body = header + "## MUST\n\n" + "\n".join(bullets) + "\n"
    return (
        "<<<SPAEX-COMPOSER-BEGIN>>>\n"
        '{"type": "composed", "questions": []}\n'
        "<<<SPAEX-COMPOSER-END>>>\n\n" + body
    )


class _Stub:
    """Routes batch vs. (non-)root merge calls by inspecting the payload
    shape, recording every call for structural assertions."""

    def __init__(self, *, root_source_hash: str, root_build_input_hash: str) -> None:
        """Initialize expected root hashes and the call recording."""
        self.calls: list[dict[str, object]] = []
        self._root_source_hash = root_source_hash
        self._root_build_input_hash = root_build_input_hash

    def __call__(self, runtime: str, prompt: str, payload: str, timeout: float) -> str:
        """Return a batch or merge response based on the payload shape."""
        data = json.loads(payload)
        self.calls.append({"runtime": runtime, "payload": data})
        if "batch_compositions" in data:
            is_root = (
                data["expected_source_hash"] == self._root_source_hash
                and data["expected_build_input_hash"] == self._root_build_input_hash
                and data["expected_source_hash"] != ""
            )
            return _merge_stub_response(payload, is_root=is_root)
        return _batch_stub_response(payload)


def _noop_operator_answer(_question: object) -> str:
    """Fail if an unexpected clarification question is raised."""
    raise AssertionError("no clarification expected in this scenario")


def _batch_stub_response_missing_first_fragment(payload: str) -> str:
    """Shape A for a batch call that cites every one of its input
    fragments except the first — reproduces the dogfooding-observed bug
    where a batch call silently drops a fragment's citation."""
    data = json.loads(payload)
    cited = data["fragments"][1:]
    bullets = "\n".join(
        f"- {f['body'].strip()} _[from `{f['molecule_id']}/{f['fragment_id']}`]_"
        for f in cited
    )
    body = f"## MUST\n\n{bullets}\n"
    return (
        "<<<SPAEX-COMPOSER-BEGIN>>>\n"
        '{"type": "composed", "questions": []}\n'
        "<<<SPAEX-COMPOSER-END>>>\n\n" + body
    )


class _FirstBatchDropsFirstFragmentStub:
    """The batch containing `mol-a` silently omits its first fragment's
    citation; every other call (a sibling batch, or a merge) composes
    normally. Records every call so a test can assert later calls never
    happen. Identifies "the batch to break" by its first fragment's
    molecule id rather than call-arrival order, since batches now dispatch
    concurrently and arrival order isn't deterministic."""

    def __init__(self) -> None:
        """Initialize the call log."""
        self.calls: list[dict[str, object]] = []

    def __call__(self, runtime: str, prompt: str, payload: str, timeout: float) -> str:
        """Return an incomplete response only for the batch containing mol-a."""
        data = json.loads(payload)
        self.calls.append({"runtime": runtime, "payload": data})
        if "batch_compositions" in data:
            return _merge_stub_response(payload, is_root=True)
        if data["fragments"][0]["molecule_id"] == "mol-a":
            return _batch_stub_response_missing_first_fragment(payload)
        return _batch_stub_response(payload)


def test_odd_batch_count_forces_multi_level_pairwise_reduction_with_carry_forward(
    tmp_path: Path,
) -> None:
    """Reduce an odd batch count with deterministic carry-forward nodes."""
    fragments = [_fragment(f"mol-{i}", f"do thing {i}.") for i in range(5)]
    limits = batching.BatchingLimits(max_fragments=1, max_bytes=100_000)
    partition_result = batching.partition(fragments, [], limits=limits)
    assert len(partition_result.batches) == 5

    source_hash = "a" * 64
    build_input_hash = "b" * 64
    # Small enough that 5 (and 3) batch bodies together don't fit, but any
    # 2 adjacent bodies do — forces the pairwise-tree path across more than
    # one level instead of one flat merge.
    merge_limits = batching.BatchingLimits(max_fragments=1_000_000, max_bytes=600)
    stub = _Stub(root_source_hash=source_hash, root_build_input_hash=build_input_hash)

    store, final_build_input_hash, outcome = composer_reduce.compose(
        partition_result=partition_result,
        source_hash=source_hash,
        build_input_hash=build_input_hash,
        repo_root=tmp_path,
        invoke_options=InvokeOptions(stub_caller=stub),
        store=ClarificationsStore(),
        prompt_hash="prompt-hash",
        operator_answer=_noop_operator_answer,
        abort_on_contradiction=True,
        limits=merge_limits,
    )

    merge_calls = [c for c in stub.calls if "batch_compositions" in c["payload"]]
    # 5 batches -> level0: pair(0,1), pair(2,3), carry 4 -> 2 merge calls.
    # level1: 3 nodes -> pair(merged01, merged23), carry 4 -> 1 merge call.
    # level2: 2 nodes -> pair(that, 4) -> 1 merge call (root).
    assert len(merge_calls) == 4
    for call in merge_calls[:-1]:
        assert len(call["payload"]["batch_compositions"]) == 2

    root_call = merge_calls[-1]
    assert root_call["payload"]["expected_source_hash"] == source_hash
    assert root_call["payload"]["expected_build_input_hash"] == build_input_hash

    # Every original runtime is identical across every call (FR-011).
    assert len({c["runtime"] for c in stub.calls}) == 1

    body = outcome.result.body
    for i in range(5):
        assert f"mol-{i}/rule" in body
    assert f'source_hash="{source_hash}"' in body


def test_oversized_merge_pair_raises_input_too_large_without_concatenation(
    tmp_path: Path,
) -> None:
    """Reject an oversized merge pair before concatenating its bodies."""
    big_body = "x" * 5_000 + "."
    fragments = [_fragment("mol-a", big_body), _fragment("mol-b", big_body)]
    limits = batching.BatchingLimits(max_fragments=1, max_bytes=100_000)
    partition_result = batching.partition(fragments, [], limits=limits)
    assert len(partition_result.batches) == 2

    source_hash = "a" * 64
    build_input_hash = "b" * 64
    merge_limits = batching.BatchingLimits(max_fragments=1_000_000, max_bytes=200)
    stub = _Stub(root_source_hash=source_hash, root_build_input_hash=build_input_hash)

    with pytest.raises(ComposerInvalidOutputError) as excinfo:
        composer_reduce.compose(
            partition_result=partition_result,
            source_hash=source_hash,
            build_input_hash=build_input_hash,
            repo_root=tmp_path,
            invoke_options=InvokeOptions(stub_caller=stub),
            store=ClarificationsStore(),
            prompt_hash="prompt-hash",
            operator_answer=_noop_operator_answer,
            abort_on_contradiction=True,
            limits=merge_limits,
        )

    assert excinfo.value.context.get("reason") == "input-too-large"
    # No merge call was ever attempted for the oversized pair.
    assert not any("batch_compositions" in c["payload"] for c in stub.calls)


def test_merge_uses_the_batch_byte_ceiling_without_extra_headroom(tmp_path: Path) -> None:
    """Use the documented batch ceiling for merge fit decisions as well."""
    fragments = [_fragment("mol-a", "x" * 100 + "."), _fragment("mol-b", "x" * 100 + ".")]
    partition_result = batching.partition(
        fragments, [], limits=batching.BatchingLimits(max_fragments=1, max_bytes=10_000)
    )
    stub = _Stub(root_source_hash="a" * 64, root_build_input_hash="b" * 64)

    with pytest.raises(ComposerInvalidOutputError) as excinfo:
        composer_reduce.compose(
            partition_result=partition_result,
            source_hash="a" * 64,
            build_input_hash="b" * 64,
            repo_root=tmp_path,
            invoke_options=InvokeOptions(stub_caller=stub),
            store=ClarificationsStore(),
            prompt_hash="prompt-hash",
            operator_answer=_noop_operator_answer,
            abort_on_contradiction=True,
            limits=batching.BatchingLimits(max_fragments=1_000_000, max_bytes=500),
        )

    assert excinfo.value.context.get("reason") == "input-too-large"
    assert not any("batch_compositions" in c["payload"] for c in stub.calls)


def test_batch_that_silently_drops_a_citation_aborts_before_the_next_batch(
    tmp_path: Path,
) -> None:
    """A batch's own response must cite every one of its input fragments; a
    drop must be caught and clearly attributed to the batch that caused it,
    before the merge step runs — even though every batch now dispatches
    concurrently, so a sibling batch is no longer skipped just because this
    one turned out incomplete (Spec 026 T020 dogfooding finding: a batch
    call can silently omit a fragment while its own progress line still
    reports it as cited, and only the final root-document check used to
    catch it — too late to say which batch dropped it)."""
    fragments = [
        _fragment("mol-a", "do thing a."),
        _fragment("mol-b", "do thing b."),
        _fragment("mol-c", "do thing c."),
    ]
    limits = batching.BatchingLimits(max_fragments=2, max_bytes=100_000)
    partition_result = batching.partition(fragments, [], limits=limits)
    assert len(partition_result.batches) == 2
    assert len(partition_result.batches[0].fragments) == 2

    stub = _FirstBatchDropsFirstFragmentStub()

    with pytest.raises(ComposerInvalidOutputError) as excinfo:
        composer_reduce.compose(
            partition_result=partition_result,
            source_hash="a" * 64,
            build_input_hash="b" * 64,
            repo_root=tmp_path,
            invoke_options=InvokeOptions(stub_caller=stub),
            store=ClarificationsStore(),
            prompt_hash="prompt-hash",
            operator_answer=_noop_operator_answer,
            abort_on_contradiction=True,
            limits=limits,
        )

    assert "mol-a/rule" in str(excinfo.value)
    # Both batches dispatch concurrently (neither waits on the other), but
    # the merge step must never run once any batch fails its own
    # completeness check.
    assert len(stub.calls) == 2
    assert not any("batch_compositions" in c["payload"] for c in stub.calls)
    log_entries = [
        json.loads(line)
        for line in (tmp_path / ".spaex" / "composer.log")
        .read_text(encoding="utf-8")
        .splitlines()
    ]
    assert log_entries[-1]["step"] == "batch-1"
    assert log_entries[-1]["invocation"] == 1


def test_batch_clarification_is_used_by_post_retry_completeness_check(
    tmp_path: Path,
) -> None:
    """A newly answered batch clarification must excuse its cited omission."""
    fragments = [
        _fragment("mol-a", "do thing a."),
        _fragment("mol-b", "do thing b."),
        _fragment("mol-c", "do thing c."),
    ]
    limits = batching.BatchingLimits(max_fragments=2, max_bytes=100_000)
    partition_result = batching.partition(fragments, [], limits=limits)
    calls: list[dict[str, object]] = []
    batch_one_attempts = 0

    def stub(runtime: str, prompt: str, payload: str, timeout: float) -> str:
        """Ask once in batch one, then omit the resolved overlap's second clause."""
        nonlocal batch_one_attempts
        data = json.loads(payload)
        calls.append(data)
        if "batch_compositions" in data:
            return _merge_stub_response(payload, is_root=True)
        if data["fragments"][0]["molecule_id"] == "mol-a":
            batch_one_attempts += 1
            if batch_one_attempts == 1:
                return (
                    "<<<SPAEX-COMPOSER-BEGIN>>>\n"
                    + json.dumps(
                        {
                            "type": "questions",
                            "questions": [
                                {
                                    "kind": "overlap",
                                    "cited_fragments": [
                                        {"molecule_id": "mol-a", "fragment_id": "rule"},
                                        {"molecule_id": "mol-b", "fragment_id": "rule"},
                                    ],
                                    "question": "Which overlapping rule wins?",
                                }
                            ],
                        }
                    )
                    + "\n<<<SPAEX-COMPOSER-END>>>\n"
                )
            return """<<<SPAEX-COMPOSER-BEGIN>>>
{"type": "composed", "questions": []}
<<<SPAEX-COMPOSER-END>>>

## MUST

- do thing a. _[from `mol-a/rule`]_
"""
        return _batch_stub_response(payload)

    store, _build_input_hash, outcome = composer_reduce.compose(
        partition_result=partition_result,
        source_hash="a" * 64,
        build_input_hash="b" * 64,
        repo_root=tmp_path,
        invoke_options=InvokeOptions(stub_caller=stub),
        store=ClarificationsStore(),
        prompt_hash="prompt-hash",
        operator_answer=lambda _question: "keep the first rule",
        abort_on_contradiction=True,
        limits=limits,
    )

    assert len(store.entries) == 1
    assert len(calls) == 4
    assert "mol-a/rule" in outcome.result.body


def test_batch_calls_dispatch_concurrently_not_sequentially(tmp_path: Path) -> None:
    """Every batch call must fire at roughly the same time, not one after
    another. Proven with a barrier every batch stub call has to reach
    together: a sequential dispatcher only ever has one call in flight, so
    the barrier's other parties never arrive and it times out."""
    fragments = [_fragment(f"mol-{i}", f"do thing {i}.") for i in range(4)]
    limits = batching.BatchingLimits(max_fragments=1, max_bytes=100_000)
    partition_result = batching.partition(fragments, [], limits=limits)
    assert len(partition_result.batches) == 4

    barrier = threading.Barrier(4, timeout=5)

    def stub(runtime: str, prompt: str, payload: str, timeout: float) -> str:
        data = json.loads(payload)
        if "batch_compositions" in data:
            return _merge_stub_response(payload, is_root=True)
        barrier.wait()
        return _batch_stub_response(payload)

    _store, _build_input_hash, outcome = composer_reduce.compose(
        partition_result=partition_result,
        source_hash="a" * 64,
        build_input_hash="b" * 64,
        repo_root=tmp_path,
        invoke_options=InvokeOptions(stub_caller=stub),
        store=ClarificationsStore(),
        prompt_hash="prompt-hash",
        operator_answer=_noop_operator_answer,
        abort_on_contradiction=True,
        limits=limits,
    )

    for i in range(4):
        assert f"mol-{i}/rule" in outcome.result.body


def test_composer_log_stays_valid_jsonlines_under_concurrent_batch_writes(
    tmp_path: Path,
) -> None:
    """Concurrent batch calls append to the same `$SPAEX_COMPOSER_LOG`; every
    line must still be its own, independently parseable JSON record - no
    interleaved writes corrupting the file."""
    fragments = [_fragment(f"mol-{i}", f"do thing {i}.") for i in range(8)]
    limits = batching.BatchingLimits(max_fragments=1, max_bytes=100_000)
    partition_result = batching.partition(fragments, [], limits=limits)
    assert len(partition_result.batches) == 8

    def stub(runtime: str, prompt: str, payload: str, timeout: float) -> str:
        data = json.loads(payload)
        if "batch_compositions" in data:
            return _merge_stub_response(payload, is_root=True)
        return _batch_stub_response(payload)

    composer_reduce.compose(
        partition_result=partition_result,
        source_hash="a" * 64,
        build_input_hash="b" * 64,
        repo_root=tmp_path,
        invoke_options=InvokeOptions(stub_caller=stub),
        store=ClarificationsStore(),
        prompt_hash="prompt-hash",
        operator_answer=_noop_operator_answer,
        abort_on_contradiction=True,
        limits=limits,
    )

    lines = (tmp_path / ".spaex" / "composer.log").read_text(encoding="utf-8").splitlines()
    entries = [json.loads(line) for line in lines]
    batch_steps = {e["step"] for e in entries if e["step"].startswith("batch-")}
    assert batch_steps == {f"batch-{i + 1}" for i in range(8)}
    assert len(entries) == 9, "eight batch records plus one merge record are expected"


def test_batch_dispatch_pins_runtime_without_rechecking_path(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """Resolve the selected runtime once for all batch and merge calls."""
    fragments = [_fragment("mol-a", "do thing a."), _fragment("mol-b", "do thing b.")]
    limits = batching.BatchingLimits(max_fragments=1, max_bytes=100_000)
    partition_result = batching.partition(fragments, [], limits=limits)
    which_calls: list[str] = []

    def fake_which(name: str) -> str | None:
        """Expose a single installed runtime and record every PATH lookup."""
        which_calls.append(name)
        return "/usr/bin/claude" if name == "claude" else None

    monkeypatch.setattr(composer_invoke.shutil, "which", fake_which)

    def fake_run(argv: list[str], *, input: str, **_kwargs: object) -> object:
        """Return scripted CLI output while preserving the real CLI path."""
        payload = input.split("COMPOSER INPUT\n---\n", 1)[1].strip()
        data = json.loads(payload)
        output = (
            _merge_stub_response(payload, is_root=True)
            if "batch_compositions" in data
            else _batch_stub_response(payload)
        )
        return composer_invoke.subprocess.CompletedProcess(argv, 0, output, "")

    monkeypatch.setattr(composer_invoke.subprocess, "run", fake_run)

    composer_reduce.compose(
        partition_result=partition_result,
        source_hash="a" * 64,
        build_input_hash="b" * 64,
        repo_root=tmp_path,
        invoke_options=InvokeOptions(),
        store=ClarificationsStore(),
        prompt_hash="prompt-hash",
        operator_answer=_noop_operator_answer,
        abort_on_contradiction=True,
        limits=limits,
    )

    assert which_calls == ["claude"]
