"""Emit format unit tests (Spec 023 T028).

Covers:

- `.spaex.md` header regex + hash pass-through.
- Section-order/provenance regex from contracts/spaex-md-format.md.
- Empty-set behavior (FR-017d).
- Hash-verification rejects composer-produced mismatches.
- `source_hash` reproducibility across fragment-input order.
- `build_input_hash` reproducibility across clarification-input order.
"""

from __future__ import annotations

import re
from pathlib import Path

import pytest

from spaex.behavior.composer.clarifications import CitedFragment, Clarification
from spaex.behavior.composer.failure import ComposerInvalidOutputError
from spaex.behavior.composer.invoke import ComposedShape
from spaex.behavior.emit import (
    SPAEX_MD_FILENAME,
    compute_build_input_hash,
    compute_source_hash,
    emit_composed,
    read_header_hashes,
    remove_if_exists,
)
from spaex.behavior.fragment import BehaviorFragment, Modality


def _fragment(molecule: str, fid: str, body: str = "**MUST** run tests.\n") -> BehaviorFragment:
    raw = (
        f"---\nid: {fid}\nkind: constitution_fragment\n"
        f"atom_source: pkg.a\nmodality: MUST\n---\n{body}"
    ).encode("utf-8")
    return BehaviorFragment.from_bytes(raw, molecule_id=molecule, path=f"{molecule}/{fid}.md")


def _valid_body(src: str, bih: str) -> str:
    return (
        f'<!-- spaex-composed:source_hash="{src}" build_input_hash="{bih}" version="1" -->\n'
        "# spaex Behavior Harness\n"
        "\n"
        "_This file is generated by `spaex install`. Do not edit by hand._\n"
        "_Change fragments in `.spaex/constitution.d/` and re-run install._\n"
        "\n"
        "## MUST\n"
        "\n"
        "- Run tests. _[from `alpha/rule-a`]_\n"
        "- Ship signed. _[from `alpha/rule-b`, `beta/rule-c`]_\n"
        "\n"
        "## SHOULD\n"
        "\n"
        "- Prefer small PRs. _[from `alpha/rule-d`]_\n"
    )


def test_emit_writes_body_verbatim_when_hashes_match(tmp_path: Path) -> None:
    src = "a" * 64
    bih = "b" * 64
    body = _valid_body(src, bih)
    outcome = emit_composed(
        ComposedShape(body=body),
        repo_root=tmp_path,
        expected_source_hash=src,
        expected_build_input_hash=bih,
    )
    assert outcome.path == tmp_path / SPAEX_MD_FILENAME
    assert outcome.source_hash == src
    assert outcome.build_input_hash == bih
    assert (tmp_path / SPAEX_MD_FILENAME).read_text(encoding="utf-8") == body


def test_emit_rejects_source_hash_mismatch(tmp_path: Path) -> None:
    body = _valid_body("a" * 64, "b" * 64)
    with pytest.raises(ComposerInvalidOutputError):
        emit_composed(
            ComposedShape(body=body),
            repo_root=tmp_path,
            expected_source_hash="c" * 64,
            expected_build_input_hash="b" * 64,
        )
    assert not (tmp_path / SPAEX_MD_FILENAME).exists()


def test_emit_rejects_build_input_hash_mismatch(tmp_path: Path) -> None:
    body = _valid_body("a" * 64, "b" * 64)
    with pytest.raises(ComposerInvalidOutputError):
        emit_composed(
            ComposedShape(body=body),
            repo_root=tmp_path,
            expected_source_hash="a" * 64,
            expected_build_input_hash="d" * 64,
        )
    assert not (tmp_path / SPAEX_MD_FILENAME).exists()


def test_emit_rejects_missing_header(tmp_path: Path) -> None:
    body = "# spaex Behavior Harness\n\n## MUST\n- Do a thing. _[from `x/y`]_\n"
    with pytest.raises(ComposerInvalidOutputError):
        emit_composed(
            ComposedShape(body=body),
            repo_root=tmp_path,
            expected_source_hash="a" * 64,
            expected_build_input_hash="b" * 64,
        )


def test_emit_rejects_wrong_header_version(tmp_path: Path) -> None:
    body = (
        '<!-- spaex-composed:source_hash="' + "a" * 64 + '" '
        'build_input_hash="' + "b" * 64 + '" version="2" -->\n'
        "# spaex Behavior Harness\n"
    )
    with pytest.raises(ComposerInvalidOutputError):
        emit_composed(
            ComposedShape(body=body),
            repo_root=tmp_path,
            expected_source_hash="a" * 64,
            expected_build_input_hash="b" * 64,
        )


def test_provenance_regex_matches_single_and_merged(tmp_path: Path) -> None:
    body = _valid_body("a" * 64, "b" * 64)
    provenance_re = re.compile(
        r"^- (?P<text>.+?)\. _\[from (?P<provenance>`[^`]+`(?:, `[^`]+`)*)\]_$",
        re.MULTILINE,
    )
    matches = provenance_re.findall(body)
    assert len(matches) == 3
    assert ("Run tests", "`alpha/rule-a`") in matches
    assert ("Ship signed", "`alpha/rule-b`, `beta/rule-c`") in matches


def test_section_order_in_composed_body(tmp_path: Path) -> None:
    body = _valid_body("a" * 64, "b" * 64)
    must_pos = body.index("## MUST\n")
    should_pos = body.index("## SHOULD\n")
    assert must_pos < should_pos


def test_source_hash_is_input_order_independent() -> None:
    a = _fragment("alpha", "rule-a", body="**MUST** run a.\n")
    b = _fragment("beta", "rule-b", body="**MUST** run b.\n")
    forward = compute_source_hash([a, b])
    reverse = compute_source_hash([b, a])
    assert forward == reverse


def test_source_hash_differs_when_body_changes() -> None:
    a1 = _fragment("alpha", "rule-a", body="**MUST** run a.\n")
    a2 = _fragment("alpha", "rule-a", body="**MUST** run a. And b.\n")
    assert compute_source_hash([a1]) != compute_source_hash([a2])


def test_source_hash_encodes_modality_none() -> None:
    raw_no_modality = (
        b"---\nid: r\nkind: constitution_fragment\natom_source: p\n---\n"
        b"**MUST** do it.\n"
    )
    without = BehaviorFragment.from_bytes(raw_no_modality, molecule_id="m")
    with_mod = _fragment("m", "r")
    assert without.modality is None
    assert with_mod.modality is Modality.MUST
    assert compute_source_hash([without]) != compute_source_hash([with_mod])


def _cited(mol: str, fid: str) -> CitedFragment:
    return CitedFragment(molecule_id=mol, fragment_id=fid, body_sha256="0" * 64)


def _clarification(key: str, answer: str = "yes") -> Clarification:
    return Clarification(
        key=key,
        question="Q?",
        cited_fragments=(_cited("mol", "frag"),),
        answer=answer,
        asked_at="2026-09-11T00:00:00Z",
        answered_at="2026-09-11T00:00:00Z",
    )


def test_build_input_hash_is_clarification_order_independent() -> None:
    c1 = _clarification("11" * 32, "answer one")
    c2 = _clarification("22" * 32, "answer two")
    forward = compute_build_input_hash(
        effective_prompt_sha256="e" * 64,
        composer_prompt_version="1",
        valid_clarifications=[c1, c2],
    )
    reverse = compute_build_input_hash(
        effective_prompt_sha256="e" * 64,
        composer_prompt_version="1",
        valid_clarifications=[c2, c1],
    )
    assert forward == reverse


def test_build_input_hash_changes_when_prompt_version_changes() -> None:
    args = {
        "effective_prompt_sha256": "e" * 64,
        "valid_clarifications": [],
    }
    v1 = compute_build_input_hash(composer_prompt_version="1", **args)
    v2 = compute_build_input_hash(composer_prompt_version="2", **args)
    assert v1 != v2


def test_build_input_hash_ignores_cosmetic_answer_whitespace() -> None:
    c_clean = _clarification("aa" * 32, "answer text")
    c_spaced = _clarification("aa" * 32, "answer text  \n")
    a = compute_build_input_hash(
        effective_prompt_sha256="e" * 64,
        composer_prompt_version="1",
        valid_clarifications=[c_clean],
    )
    b = compute_build_input_hash(
        effective_prompt_sha256="e" * 64,
        composer_prompt_version="1",
        valid_clarifications=[c_spaced],
    )
    assert a == b


def test_remove_if_exists_deletes_and_reports(tmp_path: Path) -> None:
    target = tmp_path / SPAEX_MD_FILENAME
    target.write_text("stale", encoding="utf-8")
    assert remove_if_exists(tmp_path) is True
    assert not target.exists()


def test_remove_if_exists_noop_when_absent(tmp_path: Path) -> None:
    assert remove_if_exists(tmp_path) is False


def test_read_header_hashes_returns_none_when_absent(tmp_path: Path) -> None:
    assert read_header_hashes(tmp_path) is None


def test_read_header_hashes_parses_written_file(tmp_path: Path) -> None:
    src = "1" * 64
    bih = "2" * 64
    emit_composed(
        ComposedShape(body=_valid_body(src, bih)),
        repo_root=tmp_path,
        expected_source_hash=src,
        expected_build_input_hash=bih,
    )
    assert read_header_hashes(tmp_path) == (src, bih)
