"""Map-reduce composition at scale (Spec 026 T008, T009, T012b).

T008/T009 drive the full `orchestrate.run()` entry point (materialize ->
partition -> batch/merge dispatch -> emit) via hand-built `ResolvedMolecule`
records with `cache_dir`/`molecule_manifest` populated directly, avoiding a
real git publisher clone (the pattern already used in `tests/unit` and
`tests/integration` for the resolver layer). T012b exercises
`composer_reduce.compose()` directly with a small `BatchingLimits` override
to force more than one merge-tree level end-to-end, since `orchestrate.run()`
has no seam to override the production batching ceiling.
"""

from __future__ import annotations

import json
from pathlib import Path

from spaex.behavior import orchestrate
from spaex.behavior.composer import batching
from spaex.behavior.composer import reduce as composer_reduce
from spaex.behavior.composer.clarifications import ClarificationsStore
from spaex.behavior.composer.invoke import (
    ClarificationQuestion,
    ComposedShape,
    InvokeOptions,
)
from spaex.behavior.fragment import BehaviorFragment
from spaex.constitution.resolve import ResolvedMolecule
from spaex.model.molecule_manifest import MoleculeManifest


def _resolved_molecule(cache_root: Path, index: int) -> ResolvedMolecule:
    """Create one cached resolved molecule for a scale scenario."""
    mol_id = f"mol-{index:03d}"
    cache_dir = cache_root / mol_id
    (cache_dir / "fragments").mkdir(parents=True)
    (cache_dir / "fragments" / "rule.md").write_text(
        "---\nid: rule\nkind: constitution_fragment\n"
        f"atom_source: pkg.{mol_id}\nmodality: MUST\n---\n"
        f"**MUST** follow rule {index}.\n",
        encoding="utf-8",
    )
    manifest = MoleculeManifest(
        spaex_version="4",
        id=mol_id,
        version="1.0.0",
        priority=20,
        atoms={"behavior": ("fragments/rule.md",)},
    )
    return ResolvedMolecule(
        molecule_id=mol_id,
        source_url="https://example.invalid/fixture",
        revision="0" * 40,
        repo_dir=cache_root,
        molecule_path=mol_id,
        install_hook=None,
        effective_priority=20,
        molecule_manifest=manifest,
        cache_dir=cache_dir,
    )


class _RecordingStub:
    """Deterministic Shape-A-only Composer stub, distinguishing batch calls
    (payload has `fragments`) from merge calls (payload has
    `batch_compositions`) and recording every invocation's runtime."""

    def __init__(self) -> None:
        """Initialize runtime and invocation recording."""
        self.runtimes: list[str] = []
        self.call_count = 0

    def __call__(self, runtime: str, prompt: str, payload: str, timeout: float) -> str:
        """Record the call and route its payload to the matching responder."""
        self.call_count += 1
        self.runtimes.append(runtime)
        data = json.loads(payload)
        if "batch_compositions" in data:
            return _merge_response(data)
        return _batch_response(data)


def _batch_response(data: dict) -> str:
    """Shape A for a batch OR legacy single-call payload (both carry
    `fragments`, indistinguishable from the stub's perspective). Always
    includes the header, exactly like the real canonical prompt would —
    `reduce.py`'s batch dispatch strips it for a batch call; the legacy
    single-call path needs it as-is."""
    bullets = []
    for fragment in data["fragments"]:
        scoped = f"{fragment['molecule_id']}/{fragment['fragment_id']}"
        bullets.append(f"- {fragment['body'].strip()} _[from `{scoped}`]_")
    header = (
        f'<!-- spaex-composed:source_hash="{data["expected_source_hash"]}" '
        f'build_input_hash="{data["expected_build_input_hash"]}" version="1" -->\n'
        "# spaex Behavior Harness\n\n"
        "_This file is generated by `spaex install`. Do not edit by hand._\n"
        "_Change fragments in `.spaex/constitution.d/` and re-run install._\n\n"
    )
    body = header + "## MUST\n\n" + "\n".join(bullets) + "\n"
    return (
        "<<<SPAEX-COMPOSER-BEGIN>>>\n"
        '{"type": "composed", "questions": []}\n'
        "<<<SPAEX-COMPOSER-END>>>\n\n" + body
    )


def _merge_response(data: dict) -> str:
    """Shape A for a merge call: concatenate every input body's bullets.

    Always includes the header, mirroring a real LLM following the merge
    prompt's unconditional header instruction — `reduce.py` decides whether
    to keep or strip it based on tree position, not on what the response
    contains."""
    bullets = []
    for bc in data["batch_compositions"]:
        for line in bc["body"].splitlines():
            if line.startswith("- "):
                bullets.append(line)
    header = (
        f'<!-- spaex-composed:source_hash="{data["expected_source_hash"]}" '
        f'build_input_hash="{data["expected_build_input_hash"]}" version="1" -->\n'
        "# spaex Behavior Harness\n\n"
        "_This file is generated by `spaex install`. Do not edit by hand._\n"
        "_Change fragments in `.spaex/constitution.d/` and re-run install._\n\n"
    )
    body = header + "## MUST\n\n" + "\n".join(bullets) + "\n"
    return (
        "<<<SPAEX-COMPOSER-BEGIN>>>\n"
        '{"type": "composed", "questions": []}\n'
        "<<<SPAEX-COMPOSER-END>>>\n\n" + body
    )


def test_composition_scales_across_three_or_more_batches(tmp_path: Path) -> None:
    """Compose 300 tiny fragments (well past the default byte ceiling, still
    comfortably under the fragment-count guard) through five batches."""
    repo = tmp_path / "repo"
    (repo / ".spaex").mkdir(parents=True)
    molecule_count = 300
    resolved = [_resolved_molecule(tmp_path / "cache", i) for i in range(molecule_count)]
    stub = _RecordingStub()

    outcome = orchestrate.run(
        repo_root=repo,
        state_root=tmp_path / "state",
        resolved=resolved,
        invoke_options=InvokeOptions(stub_caller=stub),
    )

    assert outcome.published
    assert outcome.fragment_count == molecule_count
    # 5 batches (~69, ~69, ~69, ~69, ~24) + 1 flat merge call = 6. A
    # count-based ceiling of 12 (the old, too-strict default) would have
    # forced 25 batches instead — exactly the over-batching the fix avoids.
    assert stub.call_count == 6
    assert len(set(stub.runtimes)) == 1, "a single runtime must answer every step (FR-011)"

    body = (repo / ".spaex" / "constitution.md").read_text(encoding="utf-8")
    for i in range(molecule_count):
        assert f"mol-{i:03d}/rule" in body


def test_single_batch_fragment_set_makes_exactly_one_composer_call(tmp_path: Path) -> None:
    """Preserve the legacy single-call path for a small fragment set."""
    repo = tmp_path / "repo"
    (repo / ".spaex").mkdir(parents=True)
    resolved = [_resolved_molecule(tmp_path / "cache", i) for i in range(2)]
    stub = _RecordingStub()

    outcome = orchestrate.run(
        repo_root=repo,
        state_root=tmp_path / "state",
        resolved=resolved,
        invoke_options=InvokeOptions(stub_caller=stub),
    )

    assert outcome.published
    assert stub.call_count == 1, "small fragment sets must not pay any batching overhead (SC-004)"


def _tree_fragment(molecule: str, index: int) -> BehaviorFragment:
    """Build one fragment for a forced multi-level merge tree."""
    raw = (
        f"---\nid: rule\nkind: constitution_fragment\n"
        f"atom_source: pkg.a\nmodality: MUST\n---\ndo thing {index}.\n"
    ).encode()
    return BehaviorFragment.from_bytes(raw, molecule_id=molecule, path=f"{molecule}/rule.md")


def test_multi_level_tree_root_is_only_result_with_full_header_and_all_citations_survive(
    tmp_path: Path,
) -> None:
    """Keep only the root header while preserving every tree citation."""
    fragments = [_tree_fragment(f"mol-{i}", i) for i in range(5)]
    partition_result = batching.partition(
        fragments, [], limits=batching.BatchingLimits(max_fragments=1, max_bytes=100_000)
    )
    assert len(partition_result.batches) == 5

    source_hash = "a" * 64
    build_input_hash = "b" * 64
    stub = _RecordingStub()

    def operator_answer(_question: ClarificationQuestion) -> str:
        """Fail if the contradiction-free tree asks a question."""
        raise AssertionError("no clarification expected in this scenario")

    store, final_build_input_hash, outcome = composer_reduce.compose(
        partition_result=partition_result,
        source_hash=source_hash,
        build_input_hash=build_input_hash,
        repo_root=tmp_path,
        invoke_options=InvokeOptions(stub_caller=stub),
        store=ClarificationsStore(),
        prompt_hash="prompt-hash",
        operator_answer=operator_answer,
        abort_on_contradiction=True,
        limits=batching.BatchingLimits(max_fragments=1_000_000, merge_max_bytes=600),
    )

    assert stub.call_count == 5 + 4  # 5 batches + the 4-call tree from test_reduce.py's math
    body = outcome.result.body
    assert f'source_hash="{source_hash}"' in body
    assert f'build_input_hash="{build_input_hash}"' in body
    for i in range(5):
        assert f"mol-{i}/rule" in body
    assert len(set(stub.runtimes)) == 1


def test_cross_batch_contradiction_at_merge_node_round_trips_and_survives_to_final_output(
    tmp_path: Path,
) -> None:
    """Round-trip a merge contradiction and retain both source citations."""
    fragments = [_tree_fragment("mol-0", 0), _tree_fragment("mol-1", 1)]
    partition_result = batching.partition(
        fragments, [], limits=batching.BatchingLimits(max_fragments=1, max_bytes=100_000)
    )
    assert len(partition_result.batches) == 2

    source_hash = "a" * 64
    build_input_hash = "b" * 64
    answer_calls = {"n": 0}

    def stub(runtime: str, prompt: str, payload: str, timeout: float) -> str:
        """Compose batches, then ask and resolve one merge question."""
        data = json.loads(payload)
        if "batch_compositions" not in data:
            return _batch_response(data)
        if not data["clarifications"]:
            question = {
                "kind": "contradiction",
                "cited_fragments": [
                    {"molecule_id": "mol-0", "fragment_id": "rule"},
                    {"molecule_id": "mol-1", "fragment_id": "rule"},
                ],
                "question": "mol-0 and mol-1 conflict; which wins?",
            }
            return (
                "<<<SPAEX-COMPOSER-BEGIN>>>\n"
                + json.dumps({"type": "questions", "questions": [question]})
                + "\n<<<SPAEX-COMPOSER-END>>>\n"
            )
        return _merge_response(data)

    def operator_answer(question: ClarificationQuestion) -> str:
        """Record and answer the expected merge contradiction."""
        answer_calls["n"] += 1
        assert question.kind == "contradiction"
        return "mol-1's rule wins"

    store, final_build_input_hash, outcome = composer_reduce.compose(
        partition_result=partition_result,
        source_hash=source_hash,
        build_input_hash=build_input_hash,
        repo_root=tmp_path,
        invoke_options=InvokeOptions(stub_caller=stub),
        store=ClarificationsStore(),
        prompt_hash="prompt-hash",
        operator_answer=operator_answer,
        abort_on_contradiction=True,
    )

    assert answer_calls["n"] == 1, "the round trip is bounded to one operator answer"
    assert len(store.entries) == 1
    assert isinstance(outcome.result, ComposedShape)
    assert "mol-0/rule" in outcome.result.body
    assert "mol-1/rule" in outcome.result.body
