"""Reproducibility: byte-identical `.spaex/constitution.md` across two installs (T031, SC-003).

Two invocations of `spaex install` on the same fixture must produce the
same `.spaex/constitution.md` bytes. The second run uses the fingerprint short-circuit
in `orchestrate.run` and does not re-invoke the Composer at all; the file
is reused unchanged.
"""

from __future__ import annotations

import json
import shutil
import subprocess
from pathlib import Path
from types import SimpleNamespace

import pytest

from spaex.behavior import orchestrate as behavior_orchestrate
from spaex.behavior.composer.invoke import (
    ComposedShape,
    ComposerInput,
    InvokeOptions,
    InvokeOutcome,
    RuntimeDescriptor,
)
from spaex.cli import add as add_cli
from spaex.cli import install as install_cli
from spaex.git.cache import clone_dir

pytestmark = pytest.mark.skipif(
    shutil.which("git") is None, reason="git binary required"
)


_MOL = "com.example.publisher.repro"
_CANONICAL = "https://example.invalid/example/publisher"


def _git(cwd: Path, *args: str) -> str:
    proc = subprocess.run(
        ["git", "-C", str(cwd), *args], capture_output=True, text=True, check=True
    )
    return proc.stdout.strip()


def _publish_repro_molecule(tmp_path: Path) -> tuple[str, str, Path]:
    working = tmp_path / "publisher-working"
    working.mkdir()
    _git(working, "init", "-q", "-b", "main")
    _git(working, "config", "user.email", "author@example.com")
    _git(working, "config", "user.name", "author")
    _git(working, "config", "commit.gpgsign", "false")

    (working / "manifest.json").write_text(
        json.dumps(
            {
                "spaex_version": "4",
                "publisher": "com.example.publisher",
                "molecules": {_MOL: {"path": "repro", "version": "1.0.0"}},
            },
            indent=2,
        )
    )
    mol_dir = working / "repro"
    mol_dir.mkdir()
    (mol_dir / "manifest.json").write_text(
        json.dumps(
            {
                "spaex_version": "4",
                "id": _MOL,
                "version": "1.0.0",
                "priority": 20,
                "atoms": {"behavior": ["fragments/a.md", "fragments/b.md"]},
            },
            indent=2,
        )
    )
    (mol_dir / "fragments").mkdir()
    (mol_dir / "fragments" / "a.md").write_text(
        "---\nid: rule-a\nkind: constitution_fragment\n"
        "atom_source: pkg.a\nmodality: MUST\n---\n"
        "**MUST** always do A.\n"
    )
    (mol_dir / "fragments" / "b.md").write_text(
        "---\nid: rule-b\nkind: constitution_fragment\n"
        "atom_source: pkg.b\nmodality: SHOULD\n---\n"
        "**SHOULD** usually do B.\n"
    )

    _git(working, "add", ".")
    _git(working, "commit", "-q", "-m", "reproducibility fixture")
    head = _git(working, "rev-parse", "HEAD")

    state_root = tmp_path / "state"
    target = clone_dir(state_root, _CANONICAL)
    target.parent.mkdir(parents=True, exist_ok=True)
    subprocess.run(
        ["git", "clone", "--bare", "-q", str(working), str(target)], check=True
    )
    return _CANONICAL, head, state_root


def _make_consumer(tmp_path: Path) -> Path:
    consumer = tmp_path / "consumer"
    consumer.mkdir()
    (consumer / ".spaex").mkdir()
    (consumer / ".spaex/manifest.json").write_text(
        json.dumps(
            {
                "spaex_version": "4",
                "identity": "com.example.project-consumer",
                "compounds": [],
            }
        )
    )
    return consumer


def _run_add(
    consumer: Path,
    state_root: Path,
    monkeypatch: pytest.MonkeyPatch,
    *,
    source_url: str,
    revision: str,
) -> int:
    monkeypatch.setenv("SPAEX_STATE", str(state_root))
    ns = SimpleNamespace(
        repo_root=str(consumer),
        source_url=source_url,
        molecule_ids=_MOL,
        revision=revision,
        all=False,
        lock_timeout=5.0,
    )
    return add_cli.run(ns)


def _run_install(
    consumer: Path, state_root: Path, monkeypatch: pytest.MonkeyPatch
) -> int:
    monkeypatch.setenv("SPAEX_STATE", str(state_root))
    ns = SimpleNamespace(repo_root=str(consumer), lock_timeout=5.0)
    return install_cli.run(ns)


class _CountingStub:
    """Counts every real Composer invocation; enforces byte-stable outputs."""

    def __init__(self) -> None:
        self.calls: int = 0

    def __call__(
        self,
        composer_input: ComposerInput,
        *,
        repo_root: Path,
        options: InvokeOptions | None = None,
    ) -> InvokeOutcome:
        self.calls += 1
        payload = composer_input.to_json()
        data = json.loads(payload)
        src = data["expected_source_hash"]
        bih = data["expected_build_input_hash"]
        header = (
            f'<!-- spaex-composed:source_hash="{src}" '
            f'build_input_hash="{bih}" version="1" -->\n'
            "# spaex Behavior Harness\n"
            "\n"
            "_This file is generated by `spaex install`. Do not edit by hand._\n"
            "_Change fragments in `.spaex/constitution.d/` and re-run install._\n"
            "\n"
        )
        must: list[str] = []
        should: list[str] = []
        for fragment in data["fragments"]:
            scoped = f"{fragment['molecule_id']}/{fragment['fragment_id']}"
            text = fragment["body"].strip().replace("**", "")
            if text.endswith("."):
                text = text[:-1]
            bullet = f"- {text}. _[from `{scoped}`]_"
            if fragment["modality"] == "SHOULD":
                should.append(bullet)
            else:
                must.append(bullet)
        parts = [header]
        if must:
            parts.append("## MUST\n\n" + "\n".join(must) + "\n\n")
        if should:
            parts.append("## SHOULD\n\n" + "\n".join(should) + "\n")
        body = "".join(parts).rstrip() + "\n"
        return InvokeOutcome(
            result=ComposedShape(body=body),
            runtime=RuntimeDescriptor(kind="stub", identifier="test"),
            raw_output=body,
        )


def test_two_installs_yield_byte_identical_spaex_md(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    canonical, head, state_root = _publish_repro_molecule(tmp_path)
    consumer = _make_consumer(tmp_path)
    stub = _CountingStub()
    monkeypatch.setattr(behavior_orchestrate, "invoke_composer", stub)

    assert (
        _run_add(consumer, state_root, monkeypatch, source_url=canonical, revision=head)
        == 0
    )
    first = (consumer / ".spaex/constitution.md").read_bytes()
    assert stub.calls == 1

    assert _run_install(consumer, state_root, monkeypatch) == 0
    second = (consumer / ".spaex/constitution.md").read_bytes()

    assert first == second, ".spaex/constitution.md must be byte-identical across two installs"
    assert stub.calls == 1, (
        "reproducibility skip must reuse the committed artifact without "
        "re-invoking the Composer when fragment set + prompt are unchanged"
    )


def test_prompt_override_invalidates_reproducibility_skip(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """Adding `.spaex/composer-prompt.md` bumps `build_input_hash` and re-composes.

    Fragment-drift invalidation (editing `.spaex/constitution.d/<f>.md` on disk
    directly) belongs to Phase 8 T050; the source path of a fragment is the
    pinned publisher tree, not the consumer's materialized copy.
    """
    canonical, head, state_root = _publish_repro_molecule(tmp_path)
    consumer = _make_consumer(tmp_path)
    stub = _CountingStub()
    monkeypatch.setattr(behavior_orchestrate, "invoke_composer", stub)

    assert (
        _run_add(consumer, state_root, monkeypatch, source_url=canonical, revision=head)
        == 0
    )
    first = (consumer / ".spaex/constitution.md").read_bytes()
    assert stub.calls == 1

    (consumer / ".spaex" / "composer-prompt.md").write_text(
        "custom prompt override for this project\n", encoding="utf-8"
    )

    assert _run_install(consumer, state_root, monkeypatch) == 0
    second = (consumer / ".spaex/constitution.md").read_bytes()

    assert first != second
    assert stub.calls == 2


# --- Spec 026 T015, T016: reproducibility holds for the multi-batch path too ---
#
# These drive `orchestrate.run()` directly with hand-built `ResolvedMolecule`
# records (`cache_dir`/`molecule_manifest` populated directly, no git clone
# needed — the pattern `ResolvedMolecule`'s own docstring names as the test
# seam for these two fields), since the property under test (determinism of
# `batching.partition()` + the map-reduce pipeline) doesn't depend on the
# resolver/git layer at all.

from spaex.constitution.resolve import ResolvedMolecule  # noqa: E402
from spaex.model.molecule_manifest import MoleculeManifest  # noqa: E402


def _multi_batch_resolved_molecules(cache_root: Path, count: int) -> list[ResolvedMolecule]:
    resolved = []
    for index in range(count):
        mol_id = f"mol-{index:03d}"
        cache_dir = cache_root / mol_id
        (cache_dir / "fragments").mkdir(parents=True)
        (cache_dir / "fragments" / "rule.md").write_text(
            "---\nid: rule\nkind: constitution_fragment\n"
            f"atom_source: pkg.{mol_id}\nmodality: MUST\n---\n"
            f"do thing {index}.\n",
            encoding="utf-8",
        )
        manifest = MoleculeManifest(
            spaex_version="4",
            id=mol_id,
            version="1.0.0",
            priority=20,
            atoms={"behavior": ("fragments/rule.md",)},
        )
        resolved.append(
            ResolvedMolecule(
                molecule_id=mol_id,
                source_url="https://example.invalid/fixture",
                revision="0" * 40,
                repo_dir=cache_root,
                molecule_path=mol_id,
                install_hook=None,
                effective_priority=20,
                molecule_manifest=manifest,
                cache_dir=cache_dir,
            )
        )
    return resolved


class _DeterministicMultiBatchStub:
    """Shape A for both batch (`fragments`) and merge (`batch_compositions`)
    payloads, always including the header (mirroring a real LLM following
    the canonical/merge prompt); `reduce.py` decides whether to keep or
    strip it. Counts invocations for the reproducibility-skip assertion."""

    def __init__(self) -> None:
        self.call_count = 0

    def __call__(self, runtime: str, prompt: str, payload: str, timeout: float) -> str:
        self.call_count += 1
        data = json.loads(payload)
        if "batch_compositions" in data:
            bullets = [
                line
                for bc in data["batch_compositions"]
                for line in bc["body"].splitlines()
                if line.startswith("- ")
            ]
        else:
            bullets = [
                f"- {f['body'].strip()} _[from `{f['molecule_id']}/{f['fragment_id']}`]_"
                for f in data["fragments"]
            ]
        header = (
            f'<!-- spaex-composed:source_hash="{data["expected_source_hash"]}" '
            f'build_input_hash="{data["expected_build_input_hash"]}" version="1" -->\n'
            "# spaex Behavior Harness\n\n"
            "_This file is generated by `spaex install`. Do not edit by hand._\n"
            "_Change fragments in `.spaex/constitution.d/` and re-run install._\n\n"
        )
        body = header + "## MUST\n\n" + "\n".join(bullets) + "\n"
        return (
            "<<<SPAEX-COMPOSER-BEGIN>>>\n"
            '{"type": "composed", "questions": []}\n'
            "<<<SPAEX-COMPOSER-END>>>\n\n" + body
        )


def test_multi_batch_reproducibility_skip_avoids_recomposition(tmp_path: Path) -> None:
    repo = tmp_path / "repo"
    (repo / ".spaex").mkdir(parents=True)
    resolved = _multi_batch_resolved_molecules(tmp_path / "cache", 25)
    stub = _DeterministicMultiBatchStub()

    first = behavior_orchestrate.run(
        repo_root=repo,
        state_root=tmp_path / "state",
        resolved=resolved,
        invoke_options=InvokeOptions(stub_caller=stub),
    )
    assert first.published
    calls_after_first_run = stub.call_count
    assert calls_after_first_run > 1, "a 25-molecule set must actually go through map-reduce"
    first_body = (repo / ".spaex" / "constitution.md").read_bytes()

    second = behavior_orchestrate.run(
        repo_root=repo,
        state_root=tmp_path / "state",
        resolved=resolved,
        invoke_options=InvokeOptions(stub_caller=stub),
    )
    assert second.published
    assert second.skipped_composer
    assert stub.call_count == calls_after_first_run, (
        "an unchanged multi-batch fragment set must hit the reproducibility "
        "skip without dispatching any batch or merge call"
    )
    assert (repo / ".spaex" / "constitution.md").read_bytes() == first_body


def test_multi_batch_forced_recomposition_is_byte_identical(tmp_path: Path) -> None:
    repo = tmp_path / "repo"
    (repo / ".spaex").mkdir(parents=True)
    resolved = _multi_batch_resolved_molecules(tmp_path / "cache", 25)
    stub = _DeterministicMultiBatchStub()

    first = behavior_orchestrate.run(
        repo_root=repo,
        state_root=tmp_path / "state",
        resolved=resolved,
        invoke_options=InvokeOptions(stub_caller=stub),
    )
    assert first.published
    first_body = (repo / ".spaex" / "constitution.md").read_bytes()

    second = behavior_orchestrate.run(
        repo_root=repo,
        state_root=tmp_path / "state",
        resolved=resolved,
        invoke_options=InvokeOptions(stub_caller=stub),
        force_composer=True,
    )
    assert second.published
    assert not second.skipped_composer
    second_body = (repo / ".spaex" / "constitution.md").read_bytes()

    assert second_body == first_body, (
        "forced recomposition of an unchanged multi-batch fragment set must "
        "be byte-identical to the original composition (SC-003)"
    )
