"""`spaex constitution trace <query>` (T057, FR-022, SC-006).

Covers both query modes contracts/cli-surface.md defines for `spaex
constitution trace`:

1. An exact scoped fragment id (`<molecule-id>/<fragment-id>`).
2. A substring of a clause's text.

...plus the explicit exit-1 cases: a bare (unscoped) fragment id is
rejected as ambiguous rather than silently treated as a substring query,
and a missing `.spaex/constitution.md` or genuinely-absent clause both report "no
match". Both `--format text` and `--format json` are exercised.

No git/molecule resolution is needed here: `constitution trace` reads
`.spaex/constitution.md`, `.spaex/constitution.d/`, and `.spaex/manifest.json` directly off
disk, so fixtures are hand-written rather than resolved through a real
publisher clone.
"""

from __future__ import annotations

import json
from pathlib import Path

from spaex.cli.main import main

_HEADER = (
    '<!-- spaex-composed:source_hash="' + "a" * 64 + '" '
    'build_input_hash="' + "b" * 64 + '" version="1" -->'
)


def _spaex_md(sections: dict[str, list[str]]) -> str:
    """Render a minimal `.spaex/constitution.md` body per contracts/spaex-md-format.md."""
    parts = [
        _HEADER,
        "# spaex Behavior Harness",
        "",
        "_This file is generated by `spaex install`. Do not edit by hand._",
        "_Change fragments in `.spaex/constitution.d/` and re-run install._",
        "",
    ]
    for modality in ("MUST", "MUST_NOT", "SHOULD", "SHOULD_NOT", "MAY", "MAY_NOT"):
        lines = sections.get(modality)
        if not lines:
            continue
        parts.append(f"## {modality}")
        parts.append("")
        parts.extend(lines)
        parts.append("")
    return "\n".join(parts).rstrip() + "\n"


def _clause(text: str, *scoped_ids: str) -> str:
    provenance = ", ".join(f"`{sid}`" for sid in scoped_ids)
    return f"- {text}. _[from {provenance}]_"


def _write_fragment(
    repo: Path,
    *,
    molecule_id: str,
    fragment_id: str,
    atom_source: str,
    modality: str,
    body: str,
) -> None:
    target_dir = repo / ".spaex" / "constitution.d" / molecule_id
    target_dir.mkdir(parents=True, exist_ok=True)
    (target_dir / f"{fragment_id}.md").write_text(
        "---\n"
        f"id: {fragment_id}\n"
        "kind: constitution_fragment\n"
        f"atom_source: {atom_source}\n"
        f"modality: {modality}\n"
        "---\n"
        f"{body}\n",
        encoding="utf-8",
    )


def _write_manifest(repo: Path, *, compounds: list[dict[str, object]]) -> None:
    (repo / ".spaex").mkdir(parents=True, exist_ok=True)
    (repo / ".spaex/manifest.json").write_text(
        json.dumps(
            {
                "spaex_version": "4",
                "identity": "com.example.trace-consumer",
                "compounds": compounds,
            },
            indent=2,
        ),
        encoding="utf-8",
    )


def _make_fixture(tmp_path: Path) -> Path:
    """One molecule, one clause, one fragment: `com.example.strict-testing/tests-before-commit`."""
    repo = tmp_path / "consumer"
    repo.mkdir()
    (repo / ".spaex").mkdir()
    (repo / ".spaex/constitution.md").write_text(
        _spaex_md(
            {
                "MUST": [
                    _clause(
                        "MUST run the project's test suite before creating "
                        "any commit",
                        "com.example.strict-testing/tests-before-commit",
                    )
                ]
            }
        ),
        encoding="utf-8",
    )
    _write_fragment(
        repo,
        molecule_id="com.example.strict-testing",
        fragment_id="tests-before-commit",
        atom_source="hooks.test-runner",
        modality="MUST",
        body="**MUST** run the project's test suite before creating any commit.",
    )
    _write_manifest(
        repo,
        compounds=[
            {
                "source": "https://github.com/haexmas/atoms",
                "revision": "a" * 40,
                "molecules": ["com.example.strict-testing"],
            }
        ],
    )
    return repo


def test_trace_exact_scoped_id_text_format(tmp_path: Path, capsys) -> None:
    repo = _make_fixture(tmp_path)
    rc = main(
        [
            "--repo-root",
            str(repo),
            "constitution",
            "trace",
            "com.example.strict-testing/tests-before-commit",
        ]
    )
    out = capsys.readouterr().out
    assert rc == 0
    assert "Modality:  MUST" in out
    assert "Sources:" in out
    assert "- com.example.strict-testing/tests-before-commit" in out
    assert "Atom:    hooks.test-runner" in out
    assert (
        f"Molecule: https://github.com/haexmas/atoms@{'a' * 40} "
        "(pinned in .spaex/manifest.json)" in out
    )


def test_trace_substring_text_format(tmp_path: Path, capsys) -> None:
    repo = _make_fixture(tmp_path)
    rc = main(
        [
            "--repo-root",
            str(repo),
            "constitution",
            "trace",
            "test suite before creating",
        ]
    )
    out = capsys.readouterr().out
    assert rc == 0
    assert "com.example.strict-testing/tests-before-commit" in out


def test_trace_bare_fragment_id_rejected_as_ambiguous(tmp_path: Path, capsys) -> None:
    """A bare `<fragment-id>` (no molecule scope) is refused, not treated as
    a substring query, even when it happens to be unique today (FR-022:
    "a bare fragment-id is not accepted, because it can be ambiguous
    across molecules")."""
    repo = _make_fixture(tmp_path)
    rc = main(
        ["--repo-root", str(repo), "constitution", "trace", "tests-before-commit"]
    )
    out = capsys.readouterr().out
    assert rc == 1
    assert "ambiguous" in out
    assert "<molecule-id>/<fragment-id>" in out


def test_trace_unknown_scoped_id_falls_back_to_substring_search(
    tmp_path: Path, capsys
) -> None:
    """A query shaped like a scoped id but not present verbatim among known
    provenance ids is not an "exact scoped fragment id" match; it still
    gets a substring search rather than an immediate refusal."""
    repo = _make_fixture(tmp_path)
    rc = main(
        [
            "--repo-root",
            str(repo),
            "constitution",
            "trace",
            "no-such-molecule/no-such-fragment",
        ]
    )
    out = capsys.readouterr().out
    assert rc == 1
    assert "no clause matches" in out


def test_trace_no_match(tmp_path: Path, capsys) -> None:
    repo = _make_fixture(tmp_path)
    rc = main(
        ["--repo-root", str(repo), "constitution", "trace", "zzz-nonexistent-zzz"]
    )
    out = capsys.readouterr().out
    assert rc == 1
    assert "no clause matches" in out


def test_trace_missing_spaex_md(tmp_path: Path, capsys) -> None:
    repo = tmp_path / "consumer"
    repo.mkdir()
    rc = main(["--repo-root", str(repo), "constitution", "trace", "anything"])
    out = capsys.readouterr().out
    assert rc == 1
    assert ".spaex/constitution.md" in out


def test_trace_json_format(tmp_path: Path, capsys) -> None:
    repo = _make_fixture(tmp_path)
    rc = main(
        [
            "--repo-root",
            str(repo),
            "constitution",
            "trace",
            "com.example.strict-testing/tests-before-commit",
            "--format",
            "json",
        ]
    )
    out = capsys.readouterr().out
    assert rc == 0
    payload = json.loads(out)
    assert len(payload["matches"]) == 1
    match = payload["matches"][0]
    assert match["modality"] == "MUST"
    assert len(match["sources"]) == 1
    source = match["sources"][0]
    assert source["scoped_id"] == "com.example.strict-testing/tests-before-commit"
    assert source["atom_source"] == "hooks.test-runner"
    assert source["molecule_source"] == "https://github.com/haexmas/atoms"
    assert source["molecule_revision"] == "a" * 40
    assert source["pinned_in"] == ".spaex/manifest.json"


def test_trace_json_no_match_reports_error(tmp_path: Path, capsys) -> None:
    repo = _make_fixture(tmp_path)
    rc = main(
        [
            "--repo-root",
            str(repo),
            "constitution",
            "trace",
            "zzz-nonexistent-zzz",
            "--format",
            "json",
        ]
    )
    out = capsys.readouterr().out
    assert rc == 1
    payload = json.loads(out)
    assert payload["matches"] == []
    assert "error" in payload and payload["error"]


def test_trace_merged_clause_with_two_provenances(tmp_path: Path, capsys) -> None:
    """A clause merged from two molecules' fragments (contracts/cli-surface.md
    sample) prints every provenance record, and its bare fragment id (shared
    by both molecules) is rejected as ambiguous."""
    repo = tmp_path / "consumer"
    repo.mkdir()
    (repo / ".spaex").mkdir()
    (repo / ".spaex/constitution.md").write_text(
        _spaex_md(
            {
                "MUST": [
                    _clause(
                        "MUST run the project's test suite before creating "
                        "any commit",
                        "com.example.strict-testing/tests-before-commit",
                        "com.example.qa-baseline/tests-before-commit",
                    )
                ]
            }
        ),
        encoding="utf-8",
    )
    _write_fragment(
        repo,
        molecule_id="com.example.strict-testing",
        fragment_id="tests-before-commit",
        atom_source="hooks.test-runner",
        modality="MUST",
        body="**MUST** run the project's test suite before creating any commit.",
    )
    _write_fragment(
        repo,
        molecule_id="com.example.qa-baseline",
        fragment_id="tests-before-commit",
        atom_source="qa.tests-before-commit",
        modality="MUST",
        body="**MUST** run the project's test suite before creating any commit.",
    )
    _write_manifest(
        repo,
        compounds=[
            {
                "source": "https://github.com/haexmas/atoms",
                "revision": "a" * 40,
                "molecules": ["com.example.strict-testing"],
            },
            {
                "source": "https://github.com/haexmas/qa-atoms",
                "revision": "b" * 40,
                "molecules": ["com.example.qa-baseline"],
            },
        ],
    )

    rc = main(
        [
            "--repo-root",
            str(repo),
            "constitution",
            "trace",
            "com.example.strict-testing/tests-before-commit",
        ]
    )
    out = capsys.readouterr().out
    assert rc == 0
    assert "- com.example.strict-testing/tests-before-commit" in out
    assert "- com.example.qa-baseline/tests-before-commit" in out
    assert "Atom:    hooks.test-runner" in out
    assert "Atom:    qa.tests-before-commit" in out
    assert f"https://github.com/haexmas/atoms@{'a' * 40}" in out
    assert f"https://github.com/haexmas/qa-atoms@{'b' * 40}" in out

    # the shared bare fragment id is ambiguous across the two molecules
    rc = main(
        ["--repo-root", str(repo), "constitution", "trace", "tests-before-commit"]
    )
    out = capsys.readouterr().out
    assert rc == 1
    assert "ambiguous" in out


def test_trace_project_local_source(tmp_path: Path, capsys) -> None:
    """A project-local fragment's provenance has no pinned molecule; the
    Molecule line names it as project-local instead of a source@revision."""
    repo = tmp_path / "consumer"
    repo.mkdir()
    (repo / ".spaex").mkdir()
    (repo / ".spaex/constitution.md").write_text(
        _spaex_md(
            {
                "SHOULD": [
                    _clause(
                        "SHOULD prefer small commits",
                        "_project/small-commits",
                    )
                ]
            }
        ),
        encoding="utf-8",
    )
    _write_fragment(
        repo,
        molecule_id="_project",
        fragment_id="small-commits",
        atom_source="_project",
        modality="SHOULD",
        body="**SHOULD** prefer small commits.",
    )
    (repo / ".spaex/manifest.json").write_text(
        json.dumps(
            {
                "spaex_version": "4",
                "identity": "com.example.trace-consumer",
                "compounds": [],
            }
        ),
        encoding="utf-8",
    )

    rc = main(
        ["--repo-root", str(repo), "constitution", "trace", "_project/small-commits"]
    )
    out = capsys.readouterr().out
    assert rc == 0
    assert "project-local" in out
