"""FR-024a: `spaex add`'s add-time plausibility check (T053).

`spaex add` of a molecule whose fragment semantically contradicts an
already-pinned molecule's fragment must not abort: the Composer's
plausibility check (a Shape B response) prints a WARN naming the
contradiction's fragments/molecules, writes `.spaex/.stale` summarizing the
finding, and the command exits 0. `.spaex.md`, already composed from the
first successful `spaex add`, is left byte-unchanged — regeneration is
deferred to the next `spaex install` (FR-024a, contracts/cli-surface.md
§add/remove).
"""

from __future__ import annotations

import json
import shutil
import subprocess
from pathlib import Path

import pytest

from spaex.behavior import orchestrate as behavior_orchestrate
from spaex.behavior.composer.invoke import (
    ClarificationQuestion,
    ComposedShape,
    ComposerInput,
    InvokeOptions,
    InvokeOutcome,
    QuestionsShape,
    RuntimeDescriptor,
)
from spaex.migrate.transform import clone_dir

pytestmark = pytest.mark.skipif(
    shutil.which("git") is None, reason="git binary required"
)

_MOL_A = "com.example.publisher.no-force-push"
_MOL_B = "com.example.publisher.rebase-flow"
_CANONICAL = "https://example.invalid/example/publisher-add-time-plausibility"


def _git(cwd: Path, *args: str) -> str:
    proc = subprocess.run(
        ["git", "-C", str(cwd), *args], capture_output=True, text=True, check=True
    )
    return proc.stdout.strip()


def _publish_two_molecules(tmp_path: Path) -> tuple[str, str, Path]:
    """Two molecules whose fragments the Composer stub treats as contradictory."""
    working = tmp_path / "publisher-working"
    working.mkdir()
    _git(working, "init", "-q", "-b", "main")
    _git(working, "config", "user.email", "author@example.com")
    _git(working, "config", "user.name", "author")
    _git(working, "config", "commit.gpgsign", "false")

    (working / "manifest.json").write_text(
        json.dumps(
            {
                "spaex_version": "4",
                "publisher": "com.example.publisher",
                "molecules": {
                    _MOL_A: {"path": "no-force-push", "version": "1.0.0"},
                    _MOL_B: {"path": "rebase-flow", "version": "1.0.0"},
                },
            },
            indent=2,
        )
    )

    mol_a_dir = working / "no-force-push"
    mol_a_dir.mkdir()
    (mol_a_dir / "manifest.json").write_text(
        json.dumps(
            {
                "spaex_version": "4",
                "id": _MOL_A,
                "version": "1.0.0",
                "priority": 20,
                "atoms": {"behavior": ["fragments/no-force-push.md"]},
            },
            indent=2,
        )
    )
    (mol_a_dir / "fragments").mkdir()
    (mol_a_dir / "fragments" / "no-force-push.md").write_text(
        "---\n"
        "id: no-force-push\n"
        "kind: constitution_fragment\n"
        "atom_source: pkg.strict-git\n"
        "modality: MUST\n"
        "---\n"
        "**MUST NOT** force-push to any branch. Ever.\n"
    )

    mol_b_dir = working / "rebase-flow"
    mol_b_dir.mkdir()
    (mol_b_dir / "manifest.json").write_text(
        json.dumps(
            {
                "spaex_version": "4",
                "id": _MOL_B,
                "version": "1.0.0",
                "priority": 30,
                "atoms": {"behavior": ["fragments/rebase-flow.md"]},
            },
            indent=2,
        )
    )
    (mol_b_dir / "fragments").mkdir()
    (mol_b_dir / "fragments" / "rebase-flow.md").write_text(
        "---\n"
        "id: rebase-flow\n"
        "kind: constitution_fragment\n"
        "atom_source: pkg.rebase-workflow\n"
        "modality: SHOULD\n"
        "---\n"
        "**SHOULD** force-push feature branches after every interactive rebase.\n"
    )

    _git(working, "add", ".")
    _git(working, "commit", "-q", "-m", "add-time plausibility fixture")
    head = _git(working, "rev-parse", "HEAD")

    state_root = tmp_path / "state"
    target = clone_dir(state_root, _CANONICAL)
    target.parent.mkdir(parents=True, exist_ok=True)
    subprocess.run(
        ["git", "clone", "--bare", "-q", str(working), str(target)], check=True
    )
    return _CANONICAL, head, state_root


def _build_shape_a_body(data: dict[str, object]) -> str:
    """Shape A body echoing the expected hashes (contracts §Shape A)."""
    header = (
        f'<!-- spaex-composed:source_hash="{data["expected_source_hash"]}" '
        f'build_input_hash="{data["expected_build_input_hash"]}" version="1" -->\n'
        "# spaex Behavior Harness\n"
        "\n"
        "_This file is generated by `spaex install`. Do not edit by hand._\n"
        "_Change fragments in `.spaex/constitution.d/` and re-run install._\n"
        "\n"
        "## MUST\n"
        "\n"
    )
    fragment = data["fragments"][0]
    scoped = f"{fragment['molecule_id']}/{fragment['fragment_id']}"
    return header + f"- Never force-push. _[from `{scoped}`]_\n"


def _make_composer_stub():
    """Shape A for one fragment (MOL_A alone); Shape B once MOL_B joins."""
    calls: list[int] = []

    def stub(
        composer_input: ComposerInput,
        *,
        repo_root: Path,
        options: InvokeOptions | None = None,
    ) -> InvokeOutcome:
        data = json.loads(composer_input.to_json())
        calls.append(len(data["fragments"]))
        if len(data["fragments"]) < 2:
            body = _build_shape_a_body(data)
            return InvokeOutcome(
                result=ComposedShape(body=body),
                runtime=RuntimeDescriptor(kind="stub", identifier="test"),
                raw_output=body,
            )
        question = ClarificationQuestion(
            kind="contradiction",
            cited_fragments=tuple(
                {"molecule_id": f["molecule_id"], "fragment_id": f["fragment_id"]}
                for f in data["fragments"]
            ),
            question=(
                "no-force-push forbids all force-push, rebase-flow requires "
                "it after interactive rebase. Which policy wins?"
            ),
        )
        return InvokeOutcome(
            result=QuestionsShape(questions=(question,)),
            runtime=RuntimeDescriptor(kind="stub", identifier="test"),
            raw_output="shape-b-stub",
        )

    return stub, calls


def test_add_of_contradicting_molecule_warns_marks_stale_and_exits_zero(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch, haex_add_helpers, capsys
) -> None:
    canonical, head, state_root = _publish_two_molecules(tmp_path)
    consumer = haex_add_helpers["make_consumer"](tmp_path)

    stub, calls = _make_composer_stub()
    monkeypatch.setattr(behavior_orchestrate, "invoke_composer", stub)

    # First add: MOL_A alone composes cleanly (Shape A).
    rc = haex_add_helpers["run_add"](
        consumer,
        state_root,
        monkeypatch,
        source_url=canonical,
        molecule_ids=_MOL_A,
        revision=head,
    )
    assert rc == 0
    assert calls == [1]
    spaex_md_path = consumer / ".spaex.md"
    assert spaex_md_path.exists()
    baseline_bytes = spaex_md_path.read_bytes()
    assert not (consumer / ".spaex" / ".stale").exists()

    capsys.readouterr()  # discard first-add output

    # Second add: MOL_B contradicts MOL_A per the stub's Shape B response.
    rc = haex_add_helpers["run_add"](
        consumer,
        state_root,
        monkeypatch,
        source_url=canonical,
        molecule_ids=_MOL_B,
        revision=head,
    )
    assert rc == 0
    assert calls == [1, 2]

    captured = capsys.readouterr()
    assert "WARN" in captured.err
    assert _MOL_A in captured.err
    assert _MOL_B in captured.err

    # `.spaex.md` is untouched: no regeneration at add-time (FR-024a).
    assert spaex_md_path.read_bytes() == baseline_bytes

    stale_path = consumer / ".spaex" / ".stale"
    assert stale_path.exists()
    stale = json.loads(stale_path.read_text())
    assert stale["schema_version"] == 1
    assert stale["detected_at"]
    assert len(stale["questions"]) == 1
    question = stale["questions"][0]
    assert question["kind"] == "contradiction"
    cited_molecules = {c["molecule_id"] for c in question["cited_fragments"]}
    assert cited_molecules == {_MOL_A, _MOL_B}

    written = json.loads((consumer / ".spaex.json").read_text())
    pinned = {mid for compound in written["compounds"] for mid in compound["molecules"]}
    assert pinned == {_MOL_A, _MOL_B}
